# Generated by Django 4.0.4 on 2022-06-08 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import my_work.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('height', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('is_resin', models.BooleanField()),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='uploads/brand/')),
                ('images', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FigureImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to=my_work.models.path_file_name)),
                ('figure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_work.figure')),
            ],
        ),
    ]
