version: '3.9'

services:
  core:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./docker_app:/core
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=websitedp
      - DB_USER=dantimefly
      - DB_PASS=Raspberry1975-
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=websitedp
      - POSTGRES_USER=dantimefly
      - POSTGRES_PASSWORD=Raspberry1975-