# Generated by Django 4.0.5 on 2022-07-08 08:42

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import printed_models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('height', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('is_resin', models.BooleanField()),
                ('description', models.TextField(max_length=3000)),
                ('webpage_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=printed_models.models.thumbnail_path_file_name)),
                ('painted_date', models.DateField(blank=True, null=True)),
                ('entry_created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrintedModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=printed_models.models.gallery_path_file_name)),
                ('figure_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='printed_models.printedmodel')),
            ],
        ),
        migrations.AddField(
            model_name='printedmodel',
            name='tags',
            field=models.ManyToManyField(null=True, to='printed_models.tag'),
        ),
    ]
