# Generated by Django 4.0.5 on 2022-07-08 13:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printed_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printedmodel',
            name='webpage_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
