# Generated by Django 4.0.5 on 2022-06-10 10:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import painted_models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('height', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('is_resin', models.BooleanField()),
                ('description', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(upload_to=painted_models.models.thumbnail_path_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='FigureImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='test_template/')),
                ('figure_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='painted_models.figure')),
            ],
        ),
    ]
