# Generated by Django 4.0.5 on 2022-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painted_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
