# Generated by Django 4.0.5 on 2022-06-26 15:30

from django.db import migrations, models
import django.utils.timezone
import painted_models.models


class Migration(migrations.Migration):

    dependencies = [
        ('painted_models', '0002_tag_figure_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figure',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='figure',
            name='painted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='figure',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=painted_models.models.thumbnail_path_file_name),
        ),
        migrations.AlterField(
            model_name='figureimages',
            name='images',
            field=models.ImageField(upload_to=painted_models.models.gallery_path_file_name),
        ),
    ]
