# Generated by Django 4.0.5 on 2022-06-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painted_models', '0003_figure_entry_created_at_figure_entry_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='painted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
