# Generated by Django 4.0.5 on 2022-06-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painted_models', '0004_alter_figure_painted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figureimages',
            old_name='images',
            new_name='image_name',
        ),
    ]
