# Generated by Django 4.0.5 on 2022-06-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painted_models', '0005_rename_images_figureimages_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
