# Generated by Django 4.0.5 on 2022-07-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/brand/')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/tools/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paints_and_tools.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/paints/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paints_and_tools.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/chemicals/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paints_and_tools.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/accessories/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paints_and_tools.brand')),
            ],
        ),
    ]
